development:
  secret_key_base: 21975ee400bf9237d7afd97f8b6308aa6f7a3a27fcc2fd1d00eef0d95b581623e134d098672d5c514d263ff4904fba2041684d899b4a69ea5f75b7358d1cc443
  aws_access_key_id: AKIAIPXOU5L662MNWBLA
  aws_secret_access_key: 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

test:
  secret_key_base: 58b288333a6cd3694f647df2e4a447f96aaf9dbc4bfb21efe6a269327848c5b3c6a6ecab3ffbf355eab5f1b061cf61a64cea10e02194165afc8d4b97a90a36ef

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: AKIAIPXOU5L662MNWBLA
  aws_secret_access_key: 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
